model_type: transformer
model:
    family: transformer
    hidden_size: 64
    num_hidden_layers: 3
    head_dim: 64
    decay_low_rank_dim: 64
    gate_low_rank_dim: 128
    a_low_rank_dim: 64 
    v_low_rank_dim: 16
    max_position_embeddings: None
    vocab_size: 5

training:
    task: linear_regression
    data: gaussian
    num_tasks: null
    num_training_examples: null
    task_kwargs: {}
    batch_size: 256
    save_every_steps: 100
    keep_every_steps: 100000
    train_steps: 10001
    learning_rate: 0.001
    lr_scheduler:
        type: "step"          # step/exponential/cosine
        gamma: 0.95           # 衰减系数（所有策略通用）
        step_size: 1000       # 仅用于step策略（每隔多少步衰减）
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 11
            inc: 2
            interval: 2000

out_dir: ./output_noLoop/linear_regression

wandb:
    name: "linear_regression_toy"
    project: in-context-training
    notes:
    log_every_steps: 10

test_run: false